sudo: required
dist: trusty
language: python
python:
  - 2.7
  - 3.5
virtualenv:
  system_site_package: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - echo $TRAVIS_PYTHON_VERSION
  - pip install -U pytest-cov
  - pip install -U h5py Pillow six numpy
  - pip install tensorflow
  - python setup.py install

script:
  - python setup.py test

matrix:
  fast_finish: true
